--- @class Vehicle A moving object, that is not a soldier.
--- A vehicle can span multiple tiles.
---
--- It can be a tank, jeep, truck, etc.
---
--- 2 tiles long.
--- 4 Tiles big 2x2
--- 6 Tiles big 3x2
--- 8 Tiles big 4x2
--- 9 Tiles big 3x3
--- 12 Tiles big 4x3
---
--- Vehicles need special Pathfinding...
---
--- https://harablog.wordpress.com/2009/01/29/clearance-based-pathfinding/
---
--- @field public x number The x position of the vehicle in pixels on the map.
--- @field public y number The y position of the vehicle in pixels on the map.
---
