--- @class Projectile  Flying object that can collide with other objects and can exlode.
--- Granate, missile, bullet, etc.
--- @field public speed number
--- @field public x number
--- @field public y number
--- @field public angle number
--- @field public start_x number
--- @field public start_y number